audiology/posts/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class SongForm(FlaskForm):
    song_name = StringField('Song Name', validators=[DataRequired()])
    artist = StringField('Artist', validators=[DataRequired()])
    year = StringField('Song Year', validators=[DataRequired()])
    submit = SubmitField('Post')

class UpdateSongForm(FlaskForm):
    song_name = StringField('Song Name', validators=[DataRequired()])
    artist = StringField('Artist', validators=[DataRequired()])
    lyrics = TextAreaField('Lyrics', validators=[DataRequired()])
    submit = SubmitField('Post')

audiology/main/routes.py
from flask import render_template, request, Blueprint
from audiology.models import Post, Song, PrivatePlaylist
from flask_login import login_user, current_user, logout_user, login_required
from audiology import db

main = Blueprint('main', __name__)

@main.route("/")
@main.route("/home") 
def home():
    if current_user.is_authenticated:
        user_playlist = PrivatePlaylist.query.filter_by(username_id=current_user.id).first()
        print(current_user.id)
    else:
        user_playlist = False
    page = request.args.get('page', 1, type=int)
    song_list = Song.query.order_by(Song.id.desc())
    songs = song_list.paginate(page=page, per_page=10)

    return render_template('home.html', song_list=song_list, songs=songs, playlist=user_playlist)
 


 

audiology/posts/routes.py
import os
import boto3
import json
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint, send_file)
from flask_login import current_user, login_required
from audiology import db
from audiology.models import Post, Album, Artist, Song, PrivatePlaylist
from audiology.posts.forms import SongForm, UpdateSongForm
from audiology.posts.audio import list_files, download_file, upload_file, get_bucket_location
from audiology.posts.song_details import (jsonprint, get_details, get_track_tags,
                                          get_track_image, get_lyrics, get_album_name,
                                          get_artist_image)

posts = Blueprint('posts', __name__)



@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = SongForm()
    if form.validate_on_submit():

        song_details = get_details({
            'method': 'track.getinfo'
        }, form.song_name.data, form.artist.data)
        song_lyrics = get_lyrics({
            'format': 'json'
        }, form.song_name.data, form.artist.data)
        song_image = get_track_image(song_details)
        song_duration = song_details.json()['track']['duration']
        song_tags = get_track_tags(song_details)

        song_file = request.files['file']
        song_file.save(os.path.join("uploads", song_file.filename))
        upload_file(f'uploads/{song_file.filename}', "audiologyfiles")
        file_location = "".join(song_file.filename.split())
        audio_path = get_bucket_location(file_location, "audiologyfiles")
        print(audio_path)
        os.remove(f'uploads/{song_file.filename}')

        artist_query = Artist.query.filter_by(name=form.artist.data).first()
        if not artist_query:
            artist = Artist(name=form.artist.data)
        else:
            artist = artist_query
        db.session.add(artist)

        if 'album' not in song_details.json()['track']:
            album_query = Album.query.filter_by(name=song_details.json()['track']['name']).first()
            album_name = song_details.json()['track']['name']
        else:
            album_query = Album.query.filter_by(
                name=song_details.json()['track']['album']['title']).first()
            album_name = song_details.json()['track']['album']['title']

        if not album_query:
            album = Album(name=album_name, 
                          year=form.year.data,
                          image_file=song_image,
                          artist=artist)
        else:
            album = album_query 
        db.session.add(album)
        song_query = Song.query.filter_by(name=form.song_name.data).first()
        if not (song_query and album_query):
            song = Song(name=form.song_name.data,
                        duration=song_duration,
                        year=form.year.data,
                        lyrics=song_lyrics,
                        audio_file=audio_path,
                        image_file=song_image,
                        artist=artist,
                        album=album)
        else:
            song = song_query
        db.session.add(song)

        playlist_query = PrivatePlaylist.query.filter_by(
            username_id=current_user.id).first()
        if not playlist_query:
            playlist = PrivatePlaylist(name=current_user.username,
                                       username=current_user)
            db.session.add(playlist) 
            playlist.songs.append(song)
        else:
            playlist = playlist_query.songs.append(song)
        
        db.session.commit()
        flash('Your song has been added.', 'success')
        return redirect(url_for("users.user_playlist", username=current_user.username))
    return render_template('create_post.html', title='New Post',
                           form=form, legend='New Post')


@posts.route("/download/<filename>", methods=["GET"])
def download(filename):
    if request.method == 'GET':
        output = download_file(filename, BUCKET)

        return send_file(output, as_attachment=True)


@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)


@posts.route("/post/<int:song_id>/update", methods=['GET', 'POST'])
@login_required
def update_song(song_id):
    song = Song.query.get_or_404(song_id)
    form = UpdateSongForm()
    if form.validate_on_submit():
        song.name = form.song_name.data
        song.artist.name = form.artist.data
        song.lyrics = form.lyrics.data
        db.session.commit()
        flash('Song has been updated.', 'success')
        return redirect(url_for('posts.update_song', song_id=song.id))
    elif request.method == 'GET':
        form.song_name.data = song.name
        form.artist.data = song.artist.name
        form.lyrics.data = song.lyrics
    return render_template('update_song.html', title='Update Song',
                           form=form, legend='Update Song')


@posts.route("/storage") 
@login_required
def storage():
    contents = list_files("audiologyfiles")
    return render_template('storage.html', contents=contents)

audiology/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from audiology import db, bcrypt
from audiology.models import User, Post, PrivatePlaylist, Song
from audiology.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from audiology.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__) 


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:  
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        user = User(username=form.username.data,
                    email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created. You are now able to log in.', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated: 
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password.', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated.', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for(
        'static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account',
                           image_file=image_file, form=form)


@users.route("/user/<string:username>")
@login_required
def user_playlist(username):

    if current_user.username != username:
        content = flash("You do not have permissions to view this user's playlist", "danger")
        return redirect(url_for("main.home"))
    page = request.args.get("page", 1, type=int)
    delete_song = request.args.get("delete_song", type=int)
    user = User.query.filter_by(username=username).first_or_404()
    songs = PrivatePlaylist.query.filter_by(username_id=user.id).first()

    if songs:
        length = len(songs.songs)
    else:
        length = 0
    if delete_song:
        for song in songs.songs:
            if song.id == delete_song:
                songs.songs.remove(song)
                db.session.commit()
                flash("Song was successfully removed from your playlist.", "success")
                return redirect(url_for("users.user_playlist", username=username))
    return render_template('user_playlist.html', songs=songs, user=user, length=length)


@users.route("/user/update")
@login_required
def update_playlist():
    add_song = request.args.get("add_song_to_playlist", type=int)
    page = request.args.get("page", 1, type=int)

    user = User.query.filter_by(username=current_user.username).first_or_404()
    playlist = PrivatePlaylist.query.filter_by(username_id=current_user.id).first()
    song_to_add = Song.query.filter_by(id=add_song).first()

    playlist.songs.append(song_to_add)
    db.session.commit()
    flash("Song was added to your playlist.", "success")
    return redirect(url_for("main.home", username=current_user.username))


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions on how to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated. You are now able to log in.', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

audiology/templates/account.html
{% extends "layout.html" %}

{% block content %}
<div class="content-section">
    <div class="media">
        <img class="rounded-circle account-img" src="{{ image_file }}">
        <div class="media-body">
            <h2 class="account-heading">{{ current_user.username }}</h2>
            <p class="text-secondary">{{ current_user.email }}</p>
        </div>
    </div>
    <form method="POST" action="" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Account Info</legend>
            <div class="form-group">
                {{ form.username.label(class="form-control-label") }}

                {% if form.username.errors %}
                {{ form.username(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.username(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                {{ form.email(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.picture.label() }}
                {{ form.picture(class="form-control-file") }}
                {% if form.picture.errors %}
                {% for error in form.picture.errors %}
                <span class="text-danger">{{ error }}</span></br>
                {% endfor %}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock content %}

audiology/templates/create_post.html
{% extends "layout.html" %}

{% block content %}

<div class="content-section">

    <form method="POST" action="" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>
            <div class="form-group">
            
                {{ form.song_name.label(class="form-control-label") }}
                {% if form.song_name.errors %}
                {{ form.song_name(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.song_name.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.song_name(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.year.label(class="form-control-label") }}
                {% if form.year.errors %}
                {{ form.year(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.year.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.year(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.artist.label(class="form-control-label") }}
                {% if form.artist.errors %}
                {{ form.artist(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.artist.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.artist(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="input-group">
                <div class="custom-file">
                    <input type="file" name="file" class="custom-file-input" id="inputGroupFile04" aria-describedby="inputGroupFileAddon04">
                    <label class="custom-file-label" for="inputGroupFile04">Choose file</label>
                </div>
            </div>            
            
        </fieldset>

        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>

{% endblock content %}

audiology/templates/home.html
{% extends "layout.html" %}
{% block content %}
<h2>All Songs</h2>
{% for song in songs.items %}

<article class="media content-section">
    <div class="media-body">

        <div class="content-container d-flex justify-content-between align-items-center">
            <div class="album-cover ">
                <img class="img-responsive" src="{{ song.image_file }}" style="width: 10rem; height: auto"> 
            </div>
            <div class="content-text flex-fill m-3 ">
                <h2><a class="article-title" >{{ song.name }}</a></h2>
                <p class="article-content">{{ song.artist.name }} </p>
                <a class="article-content btn btn-warning mr-2" href="{{ url_for('posts.update_song', song_id=song.id) }}">Edit</a>
                {% if song not in playlist.songs %}
                <a class="article-content btn btn-success" href="{{ url_for('users.update_playlist', add_song_to_playlist=song.id) }}">Add to Playlist</a>
                {% endif %}

            </div>

            <div class="audio-content align-items-center">
                <audio controls class="embed-responsive-item">
                    <source src='{{ song.audio_file }}' type="audio/mp3">
                </audio>
            </div>

        </div>
   

       
    </div>
</article>
{% endfor %}
{% for page_num in songs.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
{% if page_num %}
{% if songs.page == page_num %}
<a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
{% else %}
<a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
{% endif %}
{% else %}
...
{% endif %}
{% endfor %}
{% endblock content %}

audiology/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    {% if title %}
    <title>Audiology - {{ title }}</title>
    {% else %}
    <title>Audiology</title>
    {% endif %}
</head>

<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
            <div class="container">
                <a class="navbar-brand mr-4" href="/">Audiology</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                    aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                    <div class="navbar-nav mr-auto">
                        <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
                        {% if current_user.is_authenticated %}
                        <a class="nav-item nav-link" href="{{ url_for('users.user_playlist', username=current_user.username) }}">My Playlist</a>
                        {% endif %}
                    </div>
                    <!-- Navbar Right Side -->
                    <div class="navbar-nav">
                        {% if current_user.is_authenticated %}
                        <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                        <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                        {% else %}
                        <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                        <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <main role="main" class="container mb-4">
        <div class="row">
            <div class="col-md-12">
                {% with messages = get_flashed_messages(with_categories=True) %}
                {% if messages %}
                {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                    {{ message }}
                </div>
                {% endfor %}
                {% endif %}
                {% endwith %}
                {% block content %}{% endblock %}
            </div>
        </div>
    </main>

    <footer class="py-2 bg-dark text-white-50 fixed-bottom">
        <div class="container text-center">
            <small>Copyright &copy; Audiology 2020</small>
        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.5.1/min/dropzone.min.js">
    </script>
</body>

</html>

audiology/templates/login.html
{% extends "layout.html" %}

{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Login</legend>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                {{ form.email(class="form-control form-control-lg is-invalid")}}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {% if form.password.errors %}
                {{ form.password(class="form-control form-control-lg is-invalid")}}
                <div class="invalid-feedback">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-check">
                {{ form.remember(class="form-check-input") }}
                {{ form.remember.label(class="form-check-label") }}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
            <small class="text-muted ml-2">
                <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
            </small>
        </div>
    </form>
</div>
<div class="border-top pt-3">
    <small class="text-muted">
        Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up</a>
    </small>
</div>
{% endblock content %}

audiology/templates/post.html
{% extends "layout.html" %}

{% block content %}
<article class="media content-section">
    <img class="rounded-circle article-img"
        src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2"
                href="{{ url_for('users.user_playlist', username=post.author.username) }}">{{ post.author.username }}</a>
            <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            {% if post.author == current_user %}
            <div>
                <a class="btn btn-secondary btn-sm mt-1 mb-1"
                    href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
                <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal"
                    data-target="#deleteModal">Delete</button>
            </div>
            {% endif %}
        </div>
        <h2 class="article-title">{{ post.title }}</h2>
        <p class="article-content">{{ post.content }}</p>
    </div>
</article>
<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="container pt-2">
                <p>Once a post is deleted, it cannot be retrieved again. Are you sure?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                    <input class="btn btn-danger" type="submit" value="Delete">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

audiology/templates/reset_request.html
{% extends "layout.html" %}

{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Reset Password</legend>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                {{ form.email(class="form-control form-control-lg is-invalid")}}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock content %}

audiology/templates/user_playlist.html
{% extends "layout.html" %}
{% block content %}
{% if length != 0 %}
<div class="d-flex justify-content-between">
    <h4 class="mb-3">Playlist for {{ user.username }} ({{ length }})</h1>
        <div class="d-flex flex-row-reverse">
            <a class="btn btn-info mb-4 center" href="{{ url_for('posts.new_post') }}">Add Song</a>
        </div>
    </div>
{% else %}
<div class="d-flex justify-content-between">
    <p>Your playlist is empty. Try adding some songs!</p>
    <div class="d-flex flex-row-reverse">
        <a class="btn btn-info mb-4 center" href="{{ url_for('posts.new_post') }}">Add Song</a>
    </div>
</div>
{% endif %}
{% for song in songs.songs %}
<article class="media content-section">
    <div class="media-body">
        <div class="content-container d-flex ">
            <div class="album-cover">
                <img class = 'img-responsive' src='{{ song.image_file }}' style="width: 10rem; height: auto"> 
            </div>
            <div class="content-text m-3 ">
                <h4><a class="article-title" >{{ song.name }}</a></h4>
                <p class="article-content">{{ song.artist.name }} </p>
                
                {% if current_user.is_authenticated %}
                <a class="article-content btn btn-info" href="{{ url_for('posts.update_song', song_id=song.id) }}">Edit</a>
                <a class="article-content btn btn-danger" href="{{ url_for('users.user_playlist', username=user.username, delete_song=song.id) }}">Delete</a>  
                {% endif %} 
            </div>

            <div class="audio-content m-3 flex-fill align-items-center">
                <audio controls class="mt-3">
                    <source src='{{ song.audio_file }}' type="audio/mp3">
                </audio>
            </div>

        </div>
    </div>
</article>
{% endfor %}

{% endblock content %}